### ISSUE TITLE
SDP610 and Raspberry Pi Zero

### ISSUE THREAD

**Issue by FredyCEMIM** [Sensirion/libsensors-python#4]
I have an SDP610 and want to connect it to a Raspsberry PI Zero.
I have read that to connect this sensors with Raspberry Pi is necesary to compile a new kernell but I don't know exactly if it is necesary for the RasPi Zero and how I have to compile the kernel (I am newbie with Linux).
Could you help me, please?
Thank you very much.
Regards 
Alfredo

**Comment by kaklik** [comment]
Hello, 

You do not need to compile Linux kernel to use SDP610 sensor in Python. I am  reimplemented this sensor driver to our pymlab library. The example of usage is here: https://github.com/MLAB-project/pymlab/blob/dev/examples/diffp_example.py 
If you have some other questions, you should write to pymlab issue tracker.

**Comment by honggoff** [comment]
Depending on your use case, a Python implementation might be better suited indeed. If you would still want to use the kernel drivers, we now have a detailed tutorial that only uses the Raspberry Pi and does not involve recompiling the kernel.
